version: '2'

services:
  ci-build:
    image: microsoft/aspnetcore-build:1.1-msbuild
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore && dotnet publish -c Release -o ./obj/Docker/publish"
