apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: tweek
  name: authoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: authoring
    spec:
      containers:
      - name: authoring
        image: soluto/tweek-authoring
        ports:
        - containerPort: 3000
        env:
        - name: GIT_PUBLIC_KEY_PATH
          value: /run/secrets/tweek-secrets/tweek_ssh_public_key
        - name: GIT_PRIVATE_KEY_PATH
          value: /run/secrets/tweek-secrets/tweek_ssh_private_key
        - name: GIT_USER
          value: git
        - name: GIT_URL
          value: ssh://git@publishing/tweek/repo
        volumeMounts:
        - name: tweek-secrets
          mountPath: /run/secrets/tweek-secrets
      volumes:
        - name: tweek-secrets
          secret:
            secretName: tweek-secrets
            defaultMode: 0600
---
kind: Service
apiVersion: v1
metadata:
  namespace: tweek
  name: authoring
spec:
  type: NodePort
  selector:
    app: authoring
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30005