version: '2'

services:
  git:
    image: soluto/tweek-bare-repo
    build: ../services/git-service/BareRepository
    ports: 
      - "5001:22"
  
  publishing:
    image: soluto/tweek-publishing
    build: ../services/publishing
    logging:
      driver: "json-file"

  api:
    image: soluto/tweek-api
    build:
      context: ../
      dockerfile: TweekApiDockerfile
    logging:
      driver: "json-file"
    ports:
      - "5003:80"
      
  authoring:
    image: soluto/tweek-authoring
    build: ../services/authoring
    logging:
      driver: "json-file"
    ports:
      - "5005:3000"
      
  editor:
    image: soluto/tweek-editor
    build: ../services/editor
    logging:
      driver: "json-file"
    ports:
      - "5004:3000"

  gateway:
    image: soluto/tweek-secure-gateway
    build: ../services/secure-gateway

  zap-smoke:
    image: soluto/zap
    build: ../deployments/dev/zap
    logging:
      driver: "json-file"
    volumes:
      - ../deployments/dev/zap/session/smoke:/root/.ZAP/session/smoke
    links:
      - gateway:api
      - gateway:authoring

  zap-e2e:
    image: soluto/zap
    build: ../deployments/dev/zap
    logging:
      driver: "json-file"
    volumes:
      - ../deployments/dev/zap/session/e2e:/root/.ZAP/session/e2e
    links:
      - gateway:api
      - gateway:authoring

  smoke-tests:
    build:
      context: ../
      dockerfile: TweekApiSmokeTestDockerfile
    depends_on: 
      - gateway
      - publishing
      - zap-smoke
    environment: 
      - TWEEK_API_URL=http://api/
      - PROXY_URL=http://zap-smoke:8090

  e2e-ui:
    build: ../e2e/ui
    depends_on: 
      - selenium
      - editor
      - gateway
      - publishing
      - zap-e2e
    environment:
      - EDITOR_URL=http://editor:3000/
      - TWEEK_API_URL=http://api/
      - AUTHORING_URL=http://authoring:3000
      - GIT_PRIVATE_KEY_INLINE=eWFybiBydW4gdjEuMy4yCiQgZG9ja2VyLWNvbXBvc2UgLWYgLi9kZXBsb3ltZW50cy9kZXYvZG9ja2VyLWNvbXBvc2UueW1sIC1mIC4vZGVwbG95bWVudHMvZGV2L2RvY2tlci1jb21wb3NlLm92ZXJyaWRlLnltbCBleGVjIHB1Ymxpc2hpbmcgY2F0IC90bXAvc3NoX3NlcnZlcgotLS0tLUJFR0lOIFJTQSBQUklWQVRFIEtFWS0tLS0tDQpNSUlFcEFJQkFBS0NBUUVBeE1JdjB3QW9NTkhzc1J6OUhvanM2eUNla2w5RHI5RUt1WjUwZ3QveHk4Wk9DelFKDQplblhvbm9TeHJVK0U2a0tNUFpxVzhJUFVoN0doL0pIbTFGV3MxZVR3YTNaMStVRUZraTNROWVERklQVE8zNW5hDQpxVjBwVXJZMndLTFRXbjNzN3ZkaGNBU09YdnVqc3lxdm9sQ1BrRXFyQVV1SVFXZzV3RzBKRHVweG4vMHRSSW9xDQpPT0gxNmlmeFpZcjdEQzQvQkp2Z0g2anRrdTVuNVhNTDhBaXVnd3B3bFNTU0c4dnVldXZabW53VWRKZ3FPM0RVDQpITHVTcEZwUXUySjZGeXY4ZFVhWVQxVnRxWDloeExpSG1HRVJLaEwrNWtQRzRkMTNCb2Q1VFhWZG82eHhmQ1BhDQpoaFVuemxkTWVzQTBiL1ZhUThBaVFoa29DY1FpYk9hclU3MDNSUUlEQVFBQkFvSUJBUUNaak5ZWHU3S2h6dUlCDQpvcGJpNG9iS1JDMmNHMTVPY2p3RmVlU0JVbFYzNnExelRzdnExdU9QK2d4VExaQ1Q1UlZlNmlyTFRvWm8wemFRDQpUaWl2SXFGOFYydE00aWpWT1dvb2x6clE5L1cvYjIyVzBKSDF4RytBVGhWU3BuOTh5bk5DVnFxaTZkdFZ3dG9RDQo4OG9YU1BtUTZNU2xnUlczdmFmOFJOdGgyWktOQUg5N1k4cGpWTVgvcUxMMW5aOTVicW9yUklMUnp6S0dKanFHDQplN0VpeFQ0a0JaemxHWUF5a1dVeFFZZzBkdTlnQjc1U1o2MHNwZzVUQlh5a3RXdzVIWG1ZWlMvSHdCOVRKbG1XDQpUanlWdE9lVmxqT0ZiOFZnSHBNd3d1Mk1vcjdWUEFQd2dEWHVxRk1XdkZ6cVViSGNVS3JXMGdCSExqWFNQbVM2DQowTDFJM2NXQkFvR0JBUE94eXFKZnhyelVDUG4zcDNtWTZyNmdseVhiLytlYVhhNDY3c05ZOE1acFZkbDVtUUpWDQpuOEdRN3FYaklaa2pCU2E5YzZZQThxOFRLVHlJbEcvTDE1OFVSaFRqZldNSC9nandaem1oSmVkL0N6Lzg1Y2V4DQpsUWw3bE4vUjI0VGIzd1UxNjNtRXluaEdSVzVLd3FjVTVvRUJtbjkvWWs4aGlia2k2aEk2NEFobEFvR0JBTTZ4DQpxUFpuL25odjh1K21PZTdjelNWNUxzd2ZNM1NTc25mWGdRUlc3cnpraGtmclFaMmVYekVDbWhWTy91SlZvTWJUDQpoQS9tUXRYRzVuMk9QMndmSk1LVUNiVVZ2ZTJYNUQxU1VGYk03dWVHU3JlWExXdXJzaHdnN1p6VlpxVDYzUEJSDQpqVGtRRTRydWtWRUszTTBVUDlJTVZ3c2FEajI4K2NNUWZOTkZodFZoQW9HQUNUOXErQ1I0VHp3Z3B4TzkyRUIwDQpVQTJhRHNhOWZGV0FUcGRQN2p2V3owQzZFRW1zQThtcUNWZHRwdi9xaTN3bnV1T2ZtdUlZVTRwL214dDN2cEpXDQp1V08wa1NCYzVzQXI1THp5dmQ0ZXFSMUtHUUNJMjc0aWNMeXUxcHVKSUE2VDlRZXB5dSsrR3poWGRDc0VIZ0VPDQpDa0U4VXJCTDA4THJEZ3FFSlhMMGczMENnWUJtMHpVbUdBZ2RMRHdrQW9MUmxLQ3Q0c0pvSTZGNmZid3hLRkZ6DQpzamVrV3Q5K2ljZWp2UFRJTWU0cmFaZ2RTdEhuOTdPOElTWGdxY2xpYnRDWVhrbndUcXNobmdaVlczbmRFOFVKDQoyWHVFVEdlQk84RUp6bW1WMnIrNmhPTkNjZFpWNjR3ZzlpRnl2VW9ua2dyVUx4MnN4aHpMVmhQOW5MUjMyUXp3DQpJYWQ1SVFLQmdRRFhwYVNubHhnK28zMldBR3dHc0F4cTVDVytyRXBPOFBDRG8rUmVlNnZjRjduSWYveTRzUlB1DQo0MWlwWjZYeFlwd2dSRDd6blpqejlBZVZoRzhpQUFBQk5GVTFKRlRpWGlnUERaLzA4WUUwdGdDVmIvRU9XZnFUDQptS0NBTUgrSjJZWUlwb3NLL3dyQmRXQ1RiUHYvYUI3RkVraFFLeGVJTXYxd0trd2tSaU5BQ0E9PQ0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0NCkRvbmUgaW4gMC42NHMuCg
      - PROXY_URL=http://zap-e2e:8090
      - AUTH_DIGEST_CREDENTIALS=user:pwd

  e2e-integration:
    build: ../e2e/integration
    depends_on: 
      - gateway
      - publishing
    environment:
      - API_URL=http://api
      - AUTHORING_URL=http://authoring:3000
      - PUBLISHING_URL=http://publishing:3000
      - GIT_PRIVATE_KEY_INLINE=eWFybiBydW4gdjEuMy4yCiQgZG9ja2VyLWNvbXBvc2UgLWYgLi9kZXBsb3ltZW50cy9kZXYvZG9ja2VyLWNvbXBvc2UueW1sIC1mIC4vZGVwbG95bWVudHMvZGV2L2RvY2tlci1jb21wb3NlLm92ZXJyaWRlLnltbCBleGVjIHB1Ymxpc2hpbmcgY2F0IC90bXAvc3NoX3NlcnZlcgotLS0tLUJFR0lOIFJTQSBQUklWQVRFIEtFWS0tLS0tDQpNSUlFcEFJQkFBS0NBUUVBeE1JdjB3QW9NTkhzc1J6OUhvanM2eUNla2w5RHI5RUt1WjUwZ3QveHk4Wk9DelFKDQplblhvbm9TeHJVK0U2a0tNUFpxVzhJUFVoN0doL0pIbTFGV3MxZVR3YTNaMStVRUZraTNROWVERklQVE8zNW5hDQpxVjBwVXJZMndLTFRXbjNzN3ZkaGNBU09YdnVqc3lxdm9sQ1BrRXFyQVV1SVFXZzV3RzBKRHVweG4vMHRSSW9xDQpPT0gxNmlmeFpZcjdEQzQvQkp2Z0g2anRrdTVuNVhNTDhBaXVnd3B3bFNTU0c4dnVldXZabW53VWRKZ3FPM0RVDQpITHVTcEZwUXUySjZGeXY4ZFVhWVQxVnRxWDloeExpSG1HRVJLaEwrNWtQRzRkMTNCb2Q1VFhWZG82eHhmQ1BhDQpoaFVuemxkTWVzQTBiL1ZhUThBaVFoa29DY1FpYk9hclU3MDNSUUlEQVFBQkFvSUJBUUNaak5ZWHU3S2h6dUlCDQpvcGJpNG9iS1JDMmNHMTVPY2p3RmVlU0JVbFYzNnExelRzdnExdU9QK2d4VExaQ1Q1UlZlNmlyTFRvWm8wemFRDQpUaWl2SXFGOFYydE00aWpWT1dvb2x6clE5L1cvYjIyVzBKSDF4RytBVGhWU3BuOTh5bk5DVnFxaTZkdFZ3dG9RDQo4OG9YU1BtUTZNU2xnUlczdmFmOFJOdGgyWktOQUg5N1k4cGpWTVgvcUxMMW5aOTVicW9yUklMUnp6S0dKanFHDQplN0VpeFQ0a0JaemxHWUF5a1dVeFFZZzBkdTlnQjc1U1o2MHNwZzVUQlh5a3RXdzVIWG1ZWlMvSHdCOVRKbG1XDQpUanlWdE9lVmxqT0ZiOFZnSHBNd3d1Mk1vcjdWUEFQd2dEWHVxRk1XdkZ6cVViSGNVS3JXMGdCSExqWFNQbVM2DQowTDFJM2NXQkFvR0JBUE94eXFKZnhyelVDUG4zcDNtWTZyNmdseVhiLytlYVhhNDY3c05ZOE1acFZkbDVtUUpWDQpuOEdRN3FYaklaa2pCU2E5YzZZQThxOFRLVHlJbEcvTDE1OFVSaFRqZldNSC9nandaem1oSmVkL0N6Lzg1Y2V4DQpsUWw3bE4vUjI0VGIzd1UxNjNtRXluaEdSVzVLd3FjVTVvRUJtbjkvWWs4aGlia2k2aEk2NEFobEFvR0JBTTZ4DQpxUFpuL25odjh1K21PZTdjelNWNUxzd2ZNM1NTc25mWGdRUlc3cnpraGtmclFaMmVYekVDbWhWTy91SlZvTWJUDQpoQS9tUXRYRzVuMk9QMndmSk1LVUNiVVZ2ZTJYNUQxU1VGYk03dWVHU3JlWExXdXJzaHdnN1p6VlpxVDYzUEJSDQpqVGtRRTRydWtWRUszTTBVUDlJTVZ3c2FEajI4K2NNUWZOTkZodFZoQW9HQUNUOXErQ1I0VHp3Z3B4TzkyRUIwDQpVQTJhRHNhOWZGV0FUcGRQN2p2V3owQzZFRW1zQThtcUNWZHRwdi9xaTN3bnV1T2ZtdUlZVTRwL214dDN2cEpXDQp1V08wa1NCYzVzQXI1THp5dmQ0ZXFSMUtHUUNJMjc0aWNMeXUxcHVKSUE2VDlRZXB5dSsrR3poWGRDc0VIZ0VPDQpDa0U4VXJCTDA4THJEZ3FFSlhMMGczMENnWUJtMHpVbUdBZ2RMRHdrQW9MUmxLQ3Q0c0pvSTZGNmZid3hLRkZ6DQpzamVrV3Q5K2ljZWp2UFRJTWU0cmFaZ2RTdEhuOTdPOElTWGdxY2xpYnRDWVhrbndUcXNobmdaVlczbmRFOFVKDQoyWHVFVEdlQk84RUp6bW1WMnIrNmhPTkNjZFpWNjR3ZzlpRnl2VW9ua2dyVUx4MnN4aHpMVmhQOW5MUjMyUXp3DQpJYWQ1SVFLQmdRRFhwYVNubHhnK28zMldBR3dHc0F4cTVDVytyRXBPOFBDRG8rUmVlNnZjRjduSWYveTRzUlB1DQo0MWlwWjZYeFlwd2dSRDd6blpqejlBZVZoRzhpQUFBQk5GVTFKRlRpWGlnUERaLzA4WUUwdGdDVmIvRU9XZnFUDQptS0NBTUgrSjJZWUlwb3NLL3dyQmRXQ1RiUHYvYUI3RkVraFFLeGVJTXYxd0trd2tSaU5BQ0E9PQ0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0NCkRvbmUgaW4gMC42NHMuCg
