version: '2'

services:
  git:
    image: soluto/tweek-bare-repo
    build: ../services/git-service/BareRepository
    ports: 
      - "5001:22"
  
  publishing:
    image: soluto/tweek-publishing
    build: ../services/publishing
    logging:
      driver: "json-file"
    ports:
      - "5002:3000"

  api:
    image: soluto/tweek-api
    build:
      context: ../
      dockerfile: TweekApi.Dockerfile
    logging:
      driver: "json-file"
    ports:
      - "5003:80"
      
  authoring:
    image: soluto/tweek-authoring
    build: ../services/authoring
    logging:
      driver: "json-file"
    ports:
      - "5005:3000"
      
  editor:
    image: soluto/tweek-editor
    build: ../services/editor      
    logging:
      driver: "json-file"
    ports:
      - "5004:3000"

  gateway:
    image: soluto/tweek-gateway
    build: ../services/gateway
    volumes:
      - ../deployments/dev/gateway/config:/config
    ports:
      - "5099:80"

  smoke-tests:
    build:
      context: ../
      dockerfile: TweekApiSmokeTest.Dockerfile
    depends_on: 
      - gateway
      - publishing
    environment: 
      - TWEEK_API_URL=http://api/
    links:
      - gateway:api

  e2e-ui:
    build: ../e2e/ui
    depends_on:
      - editor
      - gateway
      - publishing
    environment:
      - GATEWAY_URL=http://gateway
      - EDITOR_URL=http://gateway
    command: [ "-c", "4", "chromium --headless --window-size='1280,720' --no-sandbox", "/src/spec" ]

  e2e-integration:
    build: ../e2e/integration
    depends_on: 
      - gateway
      - publishing
    environment:
      - GATEWAY_URL=http://gateway
      - MINIO_HOST=minio
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - MINIO_PORT=9000
      - MINIO_BUCKET=tweek
  
  oidc-server-mock:
    logging:
      driver: "json-file"
    ports: 
      - "5011:80"
